apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-worker
  namespace: bunn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-worker
  template:
    metadata:
      labels:
        app: rails-worker
    spec:
      containers:
        - name: worker
          image: bunn-rails:local-3
          imagePullPolicy: IfNotPresent
          # exec를 써서 PID 1이 rails runner가 되게(로그/시그널 처리가 깔끔)
          command: ["sh", "-lc", "exec ./bin/rails runner \"Messaging::RabbitmqConsumer.run!\""]
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILS_LOG_TO_STDOUT
              value: "1"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY_BASE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET

