apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bunn-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prairiedoggg/bunn.git
    targetRevision: HEAD
    path: k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: bunn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

